### ISSUE TITLE
The first non-comment line of the file pos_max_dist_weight.txt must contain one number for pairs(i,j) where i <> j 

### ISSUE THREAD

**Issue by seqyuan** [BDM-Lab/MOGEN#2]
Here is my command and error
`$java -jar /annoroad/data1/bioinfo/PMO/yuanzan/MOGEN/MOGEN-master/bin/3DGenerator.jar parameters_normal.txt

Reading parameters for genome..........................

The first non-comment line of the file pos_max_dist_weight.txt must contain one number for pairs(i,j) where i <> j 

Subsequent lines of the file pos_max_dist_weight.txt must contain 2 numbers in format: chromosome value

java.lang.NullPointerException
   at java.util.regex.Matcher.toMatchResult(libgcj.so.10)
   at java.util.Scanner.myCoreNext(libgcj.so.10)
   at java.util.Scanner.myPrepareForNext(libgcj.so.10)
   at java.util.Scanner.myNextLine(libgcj.so.10)
   at java.util.Scanner.hasNextLine(libgcj.so.10)
   at utility.Helper.readMatrix(Helper.java:601)
   at genomeReconstruction.GenomeGenerator.readGenomeParameters(GenomeGenerator.java:548)
   at genomeReconstruction.GenomeGenerator.initialization(GenomeGenerator.java:157)
   at genomeReconstruction.GenomeGenerator.generateStructure(GenomeGenerator.java:247)
   at genomeReconstruction.GenomeGenerator.main(GenomeGenerator.java:1022)
   at java.lang.reflect.Method.invoke(libgcj.so.10)
   at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
java.lang.NullPointerException
   at java.util.regex.Matcher.toMatchResult(libgcj.so.10)
   at java.util.Scanner.myCoreNext(libgcj.so.10)
   at java.util.Scanner.myPrepareForNext(libgcj.so.10)
   at java.util.Scanner.myNextLine(libgcj.so.10)
   at java.util.Scanner.hasNextLine(libgcj.so.10)
   at utility.Helper.readMatrix(Helper.java:601)
   at genomeReconstruction.GenomeGenerator.readGenomeParameters(GenomeGenerator.java:548)
   at genomeReconstruction.GenomeGenerator.initialization(GenomeGenerator.java:157)
   at genomeReconstruction.GenomeGenerator.generateStructure(GenomeGenerator.java:247)
   at genomeReconstruction.GenomeGenerator.main(GenomeGenerator.java:1022)
   at java.lang.reflect.Method.invoke(libgcj.so.10)
   at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
No structure is generated !
Exception in thread "main" java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Method.invoke(libgcj.so.10)
   at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
   at java.util.regex.Matcher.toMatchResult(libgcj.so.10)
   at java.util.Scanner.myCoreNext(libgcj.so.10)
   at java.util.Scanner.myPrepareForNext(libgcj.so.10)
   at java.util.Scanner.myNextLine(libgcj.so.10)
   at java.util.Scanner.hasNextLine(libgcj.so.10)
   at utility.Helper.readMatrix(Helper.java:601)
   at genomeReconstruction.GenomeGenerator.readGenomeParameters(GenomeGenerator.java:548)
   at genomeReconstruction.GenomeGenerator.initialization(GenomeGenerator.java:157)
   at genomeReconstruction.GenomeGenerator.generateStructure(GenomeGenerator.java:247)
   at genomeReconstruction.GenomeGenerator.main(GenomeGenerator.java:1022)
   at java.lang.reflect.Method.invoke(libgcj.so.10)
   ...1 more
`

my pos_max_dist_weight.txt is this:
`#the first coefficient is for all (chr1,chr2) where chr1 != chr2
1.0
##coefficients for intrachromosomal contacts of chromosomes
1 1.0
2 1.0
3 1.0
4 1.0
5 1.0
`
pos_min_dist_weight.txt
`#the first coefficient is for all (chr1,chr2) where chr1 != chr2
2.0
#coefficients for intrachromosomal contacts of chromosomes
1 4.0
2 4.0
3 4.0
4 4.0
5 4.0
`
neg_max_dist_weight.txt
`#the first coefficient is for all (chr1,chr2) where chr1 != chr2
0.5
#coefficients for intrachromosomal contacts of chromosome
1 5.0
2 5.0
3 5.0
4 5.0
5 5.0
`

neg_min_dist_weight.txt
`#the first coefficient is for all (chr1,chr2) where chr1 != chr2
0.5
#coefficients for intrachromosomal contacts of chromosomes
1 1.2
2 1.35
3 2.2
4 2.2
5 2.0
`
chr_upper_bound_id.txt
`1 31
2 51
3 75
4 94
5 121
`

what should I do?

**Comment by tuantrieu** [comment]
Have you tried to go into the folder /annoroad/data1/bioinfo/PMO/yuanzan/MOGEN/MOGEN-master/bin/ (cd /annoroad/data1/bioinfo/PMO/yuanzan/MOGEN/MOGEN-master/bin/) and run java -jar ..?

**Comment by Rayko87** [comment]
Hello tuantrieu. I have the same problem and I run the program from the same folder:

java -jar 3DGenerator.jar /mnt/data/robert/programs/MOGEN/MOGEN/examples/hiC/parameters_chr1_1mb_normal.txt

This is one of your examples, from the cloned git, but I got the same error.
